databases:
  - name: portfolio
    plan: free
    databaseName: portfolio
    user: portfolio

services:
  - type: web
    plan: free
    name: portfolio
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false